"""Public package metadata for the Urdu document OCR reimplementation."""

import logging as _logging

from urdu_document_ocr.config import (
    DatasetSplitConfig,
    InferenceConfig,
    InputLimitsConfig,
    MorphologyOperation,
    PreprocessingConfig,
    RecognizerConfig,
    SegmentationConfig,
    SyntheticDataConfig,
    ThresholdMethod,
    TrainingConfig,
)
from urdu_document_ocr.data import (
    DatasetPartition,
    DatasetSplitResult,
    DatasetStatistics,
    DatasetValidationReport,
    FixtureGenerationResult,
    GeneratedLineSample,
    GeneratedPageFixture,
    PageLayoutFamily,
    ReviewDecision,
    ReviewStatus,
    ShapingCapabilities,
    SplitCounts,
    SyntheticLineRecord,
    SyntheticPageLine,
    SyntheticPageRecord,
    TextSource,
    ValidationIssue,
    ValidationSeverity,
    apply_review_overlay,
    assert_shaping_available,
    build_vocabulary,
    bundled_font_path,
    dataset_fingerprint,
    find_unseen_characters,
    generate_fixture_dataset,
    generate_line_dataset,
    generate_line_sample,
    generate_page_fixture,
    load_font_provenance,
    load_vocabulary,
    normalize_transcription,
    read_manifest,
    read_review_overlay,
    review_overlay_fingerprint,
    save_vocabulary,
    split_dataset,
    validate_dataset,
    write_manifest,
    write_review_overlay,
    write_split_manifests,
)
from urdu_document_ocr.document import (
    assemble_document,
    assemble_page,
    document_to_dict,
    document_to_json,
    document_to_text,
    load_document,
    write_json_result,
    write_text_result,
)
from urdu_document_ocr.errors import (
    AssemblyError,
    BenchmarkError,
    CheckpointError,
    CTCAlignmentError,
    DatasetSplitError,
    DatasetValidationError,
    DecodingError,
    DocumentLoadError,
    EvaluationError,
    ManifestError,
    ModelInputError,
    PdfPasswordError,
    PdfRenderError,
    PreprocessingError,
    RecognitionError,
    ResourceLimitError,
    ReviewOverlayError,
    SegmentationError,
    SyntheticDataError,
    TrainingDataError,
    TrainingError,
    UnsupportedDocumentFormatError,
    UrduOCRError,
    VocabularyError,
)
from urdu_document_ocr.evaluation import (
    BENCHMARK_SCHEMA_VERSION,
    METRIC_POLICY_FINGERPRINT,
    METRIC_POLICY_ID,
    RECOGNITION_BENCHMARK_VERSION,
    VISION_BENCHMARK_VERSION,
    AlignmentStep,
    CharacterFrequency,
    EditOperation,
    ErrorAnalysis,
    EvaluationReport,
    ExpectedRegion,
    RegionMatch,
    SampleEvaluation,
    SubstitutionConfusion,
    VisionBenchmarkCase,
    VisionBenchmarkResult,
    align_sequences,
    analyze_errors,
    ascii_space_tokens,
    build_artifact_manifest,
    canonical_fingerprint,
    character_error_rate,
    edit_counts,
    edit_distance,
    evaluate_checkpoint,
    evaluate_predictions,
    evaluate_text,
    exact_match,
    match_regions,
    read_benchmark_json,
    render_recognition_dataset,
    render_vision_cases,
    run_vision_benchmark,
    verify_artifact_manifest,
    verify_benchmark_results,
    verify_frozen_sources,
    vision_logical_manifest,
    word_error_rate,
    write_canonical_json,
)
from urdu_document_ocr.pipeline import recognize_document, recognize_page
from urdu_document_ocr.types import (
    DatasetSample,
    DocumentOCRResult,
    EditCounts,
    EvaluationResult,
    LineOCRResult,
    OCRPrediction,
    PageImage,
    PageOCRResult,
    PreprocessedPage,
    SourceMetadata,
    SourceType,
    Vocabulary,
)
from urdu_document_ocr.vision import extract_line_crop, preprocess_page, segment_page

__version__ = "0.1.0"

_logging.getLogger(__name__).addHandler(_logging.NullHandler())

_RECOGNITION_EXPORTS = frozenset(
    {
        "CRNNRecognizer",
        "CTCAlignmentReport",
        "LoadedRecognizer",
        "OCRRecognizer",
        "RecognizerOutput",
        "compute_ctc_loss",
        "greedy_ctc_decode",
        "input_width_to_timesteps",
        "load_recognizer",
        "minimum_ctc_timesteps",
        "prepare_line_image",
        "recognize_line",
        "recognize_lines",
        "validate_ctc_alignment",
    }
)

_TRAINING_EXPORTS = frozenset(
    {
        "CHECKPOINT_SCHEMA_VERSION",
        "CheckpointMetadata",
        "OCRBatch",
        "OCRLineDataset",
        "OCRLineItem",
        "OCRTrainer",
        "TrainingEpochRecord",
        "TrainingPreflightReport",
        "TrainingResult",
        "collate_ocr_batch",
        "load_checkpoint",
        "load_checkpoint_model",
        "save_checkpoint",
        "set_training_seed",
        "train_model",
        "validate_training_data",
    }
)


def __getattr__(name: str) -> object:
    """Load optional recognition or training objects only when requested."""

    if name not in _RECOGNITION_EXPORTS | _TRAINING_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    try:
        if name in _RECOGNITION_EXPORTS:
            from urdu_document_ocr import recognition as optional_module
        else:
            from urdu_document_ocr import training as optional_module
    except ModuleNotFoundError as error:
        if error.name in {"safetensors", "torch"}:
            raise ImportError(
                "PyTorch recognition and training support is optional; "
                "install urdu-document-ocr[ml]"
            ) from error
        raise
    value = getattr(optional_module, name)
    globals()[name] = value
    return value


__all__ = [
    "BENCHMARK_SCHEMA_VERSION",
    "CHECKPOINT_SCHEMA_VERSION",
    "METRIC_POLICY_FINGERPRINT",
    "METRIC_POLICY_ID",
    "RECOGNITION_BENCHMARK_VERSION",
    "VISION_BENCHMARK_VERSION",
    "AlignmentStep",
    "AssemblyError",
    "BenchmarkError",
    "CRNNRecognizer",
    "CTCAlignmentError",
    "CTCAlignmentReport",
    "CharacterFrequency",
    "CheckpointError",
    "CheckpointMetadata",
    "DatasetPartition",
    "DatasetSample",
    "DatasetSplitConfig",
    "DatasetSplitError",
    "DatasetSplitResult",
    "DatasetStatistics",
    "DatasetValidationError",
    "DatasetValidationReport",
    "DecodingError",
    "DocumentLoadError",
    "DocumentOCRResult",
    "EditCounts",
    "EditOperation",
    "ErrorAnalysis",
    "EvaluationError",
    "EvaluationReport",
    "EvaluationResult",
    "ExpectedRegion",
    "FixtureGenerationResult",
    "GeneratedLineSample",
    "GeneratedPageFixture",
    "InferenceConfig",
    "InputLimitsConfig",
    "LineOCRResult",
    "LoadedRecognizer",
    "ManifestError",
    "ModelInputError",
    "MorphologyOperation",
    "OCRBatch",
    "OCRLineDataset",
    "OCRLineItem",
    "OCRPrediction",
    "OCRRecognizer",
    "OCRTrainer",
    "PageImage",
    "PageLayoutFamily",
    "PageOCRResult",
    "PdfPasswordError",
    "PdfRenderError",
    "PreprocessedPage",
    "PreprocessingConfig",
    "PreprocessingError",
    "RecognitionError",
    "RecognizerConfig",
    "RecognizerOutput",
    "RegionMatch",
    "ResourceLimitError",
    "ReviewDecision",
    "ReviewOverlayError",
    "ReviewStatus",
    "SampleEvaluation",
    "SegmentationConfig",
    "SegmentationError",
    "ShapingCapabilities",
    "SourceMetadata",
    "SourceType",
    "SplitCounts",
    "SubstitutionConfusion",
    "SyntheticDataConfig",
    "SyntheticDataError",
    "SyntheticLineRecord",
    "SyntheticPageLine",
    "SyntheticPageRecord",
    "TextSource",
    "ThresholdMethod",
    "TrainingConfig",
    "TrainingDataError",
    "TrainingEpochRecord",
    "TrainingError",
    "TrainingPreflightReport",
    "TrainingResult",
    "UnsupportedDocumentFormatError",
    "UrduOCRError",
    "ValidationIssue",
    "ValidationSeverity",
    "VisionBenchmarkCase",
    "VisionBenchmarkResult",
    "Vocabulary",
    "VocabularyError",
    "__version__",
    "align_sequences",
    "analyze_errors",
    "apply_review_overlay",
    "ascii_space_tokens",
    "assemble_document",
    "assemble_page",
    "assert_shaping_available",
    "build_artifact_manifest",
    "build_vocabulary",
    "bundled_font_path",
    "canonical_fingerprint",
    "character_error_rate",
    "collate_ocr_batch",
    "compute_ctc_loss",
    "dataset_fingerprint",
    "document_to_dict",
    "document_to_json",
    "document_to_text",
    "edit_counts",
    "edit_distance",
    "evaluate_checkpoint",
    "evaluate_predictions",
    "evaluate_text",
    "exact_match",
    "extract_line_crop",
    "find_unseen_characters",
    "generate_fixture_dataset",
    "generate_line_dataset",
    "generate_line_sample",
    "generate_page_fixture",
    "greedy_ctc_decode",
    "input_width_to_timesteps",
    "load_checkpoint",
    "load_checkpoint_model",
    "load_document",
    "load_font_provenance",
    "load_recognizer",
    "load_vocabulary",
    "match_regions",
    "minimum_ctc_timesteps",
    "normalize_transcription",
    "prepare_line_image",
    "preprocess_page",
    "read_benchmark_json",
    "read_manifest",
    "read_review_overlay",
    "recognize_document",
    "recognize_line",
    "recognize_lines",
    "recognize_page",
    "render_recognition_dataset",
    "render_vision_cases",
    "review_overlay_fingerprint",
    "run_vision_benchmark",
    "save_checkpoint",
    "save_vocabulary",
    "segment_page",
    "set_training_seed",
    "split_dataset",
    "train_model",
    "validate_ctc_alignment",
    "validate_dataset",
    "validate_training_data",
    "verify_artifact_manifest",
    "verify_benchmark_results",
    "verify_frozen_sources",
    "vision_logical_manifest",
    "word_error_rate",
    "write_canonical_json",
    "write_json_result",
    "write_manifest",
    "write_review_overlay",
    "write_split_manifests",
    "write_text_result",
]
