"""Public package metadata for the Urdu document OCR reimplementation."""

import logging as _logging

from urdu_document_ocr.config import (
    DatasetSplitConfig,
    InputLimitsConfig,
    MorphologyOperation,
    PreprocessingConfig,
    SegmentationConfig,
    ThresholdMethod,
)
from urdu_document_ocr.data import (
    DatasetPartition,
    DatasetSplitResult,
    DatasetStatistics,
    DatasetValidationReport,
    ReviewDecision,
    ReviewStatus,
    SplitCounts,
    ValidationIssue,
    ValidationSeverity,
    apply_review_overlay,
    build_vocabulary,
    dataset_fingerprint,
    find_unseen_characters,
    load_vocabulary,
    normalize_transcription,
    read_manifest,
    read_review_overlay,
    review_overlay_fingerprint,
    save_vocabulary,
    split_dataset,
    validate_dataset,
    write_manifest,
    write_review_overlay,
    write_split_manifests,
)
from urdu_document_ocr.document import load_document
from urdu_document_ocr.errors import (
    DatasetSplitError,
    DatasetValidationError,
    DocumentLoadError,
    ManifestError,
    PdfPasswordError,
    PdfRenderError,
    PreprocessingError,
    ResourceLimitError,
    ReviewOverlayError,
    SegmentationError,
    UnsupportedDocumentFormatError,
    UrduOCRError,
    VocabularyError,
)
from urdu_document_ocr.types import (
    DatasetSample,
    PageImage,
    PreprocessedPage,
    SourceMetadata,
    SourceType,
    Vocabulary,
)
from urdu_document_ocr.vision import extract_line_crop, preprocess_page, segment_page

__version__ = "0.1.0"

_logging.getLogger(__name__).addHandler(_logging.NullHandler())

__all__ = [
    "DatasetPartition",
    "DatasetSample",
    "DatasetSplitConfig",
    "DatasetSplitError",
    "DatasetSplitResult",
    "DatasetStatistics",
    "DatasetValidationError",
    "DatasetValidationReport",
    "DocumentLoadError",
    "InputLimitsConfig",
    "ManifestError",
    "MorphologyOperation",
    "PageImage",
    "PdfPasswordError",
    "PdfRenderError",
    "PreprocessedPage",
    "PreprocessingConfig",
    "PreprocessingError",
    "ResourceLimitError",
    "ReviewDecision",
    "ReviewOverlayError",
    "ReviewStatus",
    "SegmentationConfig",
    "SegmentationError",
    "SourceMetadata",
    "SourceType",
    "SplitCounts",
    "ThresholdMethod",
    "UnsupportedDocumentFormatError",
    "UrduOCRError",
    "ValidationIssue",
    "ValidationSeverity",
    "Vocabulary",
    "VocabularyError",
    "__version__",
    "apply_review_overlay",
    "build_vocabulary",
    "dataset_fingerprint",
    "extract_line_crop",
    "find_unseen_characters",
    "load_document",
    "load_vocabulary",
    "normalize_transcription",
    "preprocess_page",
    "read_manifest",
    "read_review_overlay",
    "review_overlay_fingerprint",
    "save_vocabulary",
    "segment_page",
    "split_dataset",
    "validate_dataset",
    "write_manifest",
    "write_review_overlay",
    "write_split_manifests",
]
